### ISSUE TITLE
Work Term Tasks

### ISSUE THREAD

**Issue by Nat1405** [ijiraq/gemini_processing#1]
Some questions about testing that will be developed later.
 - Learn to build a container that	can run	the current version of nifty
 - Build said conatiner.
 - Modify nifty	to use the cadc-tap system to query files.
 - Use cadc-data to get those files. < - then orgnize using nifty script
 - Get the container loaded into ARCADE	with a cavern storage allocation.
 - Use the new script to inside	ARCADE to process some data.
 - Work	on Data	Engineering to allow data to go	into CAOM2.
 - Give	end of work term presentation.

**Comment by ijiraq** [comment]
That quite a list of tasks for a 'first day' ..

**Comment by ijiraq** [comment]
I removed this from the Build a Nifty Arcade Container as that 'project' is nearly done but these actions are for the full term.
