### ISSUE TITLE
Graphics in Nifty Container

### ISSUE THREAD

**Issue by Nat1405** [ijiraq/gemini_processing#12]
So far graphical IRAF tasks aren't working in the Arcade version of Nifty. They are working in a non-container version of Nifty though. @ijiraq do we want graphical tasks in Arcade?

![image](https://user-images.githubusercontent.com/17349431/81605165-e92a0500-9385-11ea-9c08-86b5ba6a2f76.png)

**Comment by dbohlender** [comment]
I think that if the idea of the Arcade version is eventually to have PI's use it to process their own data then they will expect graphical tasks to work.

**Comment by ijiraq** [comment]
yes, we want those working for PIs.   

When setting up the docker container we might need to add 'x11', not sure its included by default?   I thought on arcade the 'xterm' was the launch CMD?  So likely X is available.  

What's the error when running on Arcade?

**Comment by Nat1405** [comment]
Perfect, sounds good. You're right, I'll try adding x11 and see how that goes.

[Here's a screenshot of the error](https://user-images.githubusercontent.com/17349431/81605165-e92a0500-9385-11ea-9c08-86b5ba6a2f76.png).

**Comment by ijiraq** [comment]
This:


![](https://user-images.githubusercontent.com/17349431/81605165-e92a0500-9385-11ea-9c08-86b5ba6a2f76.png)

Looks more like a file-not-found error than a display error?

**Comment by Nat1405** [comment]
Looks like it might have been a permissions error on /cavern/home/Nat; graphical tasks (and IRAF!) look to be working in /scratch within the container. The next thing I plan to do is setup the container with a version of Nifty supporting graphical tasks, push to Dockerhub, and see if it all works.

![image](https://user-images.githubusercontent.com/17349431/81731910-7f246500-9444-11ea-8057-42b92088dcf8.png)

**Comment by Nat1405** [comment]
Looks like we have graphics tasks working in Nifty! Adding xterm to the container and making a few changes to the Nifty source code fixed them.s

![image](https://user-images.githubusercontent.com/17349431/81833663-d8e46800-94f4-11ea-86cf-406846e87cb9.png)
