### ISSUE TITLE
Find some QA assistances

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#13]
We need help setting up QA process.  Marie at Gemini should be able to help with that.  Get in-touch and find out.

**Comment by Nat1405** [comment]
I can do parts of this too if you like JJ, I've kept in touch with Marie over the years.

**Comment by Nat1405** [comment]
Marie didn't raise any complaints with the uncorrected datacubes. She wanted a few things double checked with the telluric correction and cube merging. If we only archive un-corrected cubes, we're probably safe.
