### ISSUE TITLE
Need a process for persisting data to VOSpace that is configurable.

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#14]
The new `vos` package allows setting the VOSpace destination using a config.  

modify the scripts to do the processing on a local disk but then copy the resulting file to a VOSpace area, the VOSpace should be set configured inside the VM or container.

**Comment by Nat1405** [comment]
Currently working on this and getting a feel for VOSpace. Noticed that large .fits files don't seem to be copying over with vcp:

![image](https://user-images.githubusercontent.com/17349431/81872981-aefc6700-952f-11ea-9785-f9cd9d85a8e6.png)

I'm going to retry with vsync for now.

**Comment by Nat1405** [comment]
Maybe I'm using vsync wrong but it doesn't appear to be working on files over 1MB in size. I think I'm stalled on this one.

![image](https://user-images.githubusercontent.com/17349431/81874308-79a54880-9532-11ea-8868-6bb40e20749b.png)

**Comment by dbohlender** [comment]
I hope someone didn't miss a '0' when allocating space?
