### ISSUE TITLE
Run the container in batch mode

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#15]
We need to run a few 100 jobs with this processing.  To do this we can build a VM that has docker on it and then run these jobs as `docker run` jobs on that VM.

**Comment by sfabbro** [comment]
Making the VM and run docker run should work as a hack short term solution, but not long term. Here are some quick thoughts onto what to check:
- the container image has to be on the VM image (not on a separate volume)
- the user running the batch job should have access to the container image and can execute docker run
- mount properly the ephemeral partition at container runtime
- make sure the container exits cleanly when one job ends (as a success or as failure)

**Comment by ijiraq** [comment]
> * the container image has to be on the VM image (not on a separate volume)

Could the VM pull the container from Docker at run time?  It might be quick enough?

**Comment by sfabbro** [comment]
> > * the container image has to be on the VM image (not on a separate volume)
> 
> Could the VM pull the container from Docker at run time? It might be quick enough?

A script on the VM could pull the image at run time but:
*  the container registry is not on the same network, and the batch system would pull hundreds of images simultaneously
* we would have to make sure there is only one image per VM while there may be several jobs on the VM.

**Comment by Nat1405** [comment]
Hi all, I'm just playing around in Batch and noticed I have a year-old VM in there (not sure how it got there). @dbohlender does this belong to you? I'm just checking before I delete it.

![image](https://user-images.githubusercontent.com/17349431/81847576-a47aa700-9508-11ea-81bf-846b4f523afe.png)

**Comment by dbohlender** [comment]
Yes, go ahead and delete it.  About once a year I try to use a VM to generate some non-LTE model atmospheres and spectrum synthesis.  And then forget how to do it again...

**Comment by Nat1405** [comment]
Perfect, thank you!! (Ha, sounds like a job for a container...........)

**Comment by dbohlender** [comment]
Yes, exactly!!!

**Comment by Nat1405** [comment]
> > > * the container image has to be on the VM image (not on a separate volume)
> > 
> > 
> > Could the VM pull the container from Docker at run time? It might be quick enough?
> 
> A script on the VM could pull the image at run time but:
> 
> * the container registry is not on the same network, and the batch system would pull hundreds of images simultaneously
> * we would have to make sure there is only one image per VM while there may be several jobs on the VM.

@sfabbro thanks for your help. Could you elaborate on why there should only be one image per VM? Is that just to limit unnecessary downloads of the container image(say, from DockerHub)?

**Comment by Nat1405** [comment]
Also to make sure I'm not just going down a rabbit hole, @ijiraq @dbohlender I'm following the instructions [here](https://www.canfar.net/en/docs/quick_start/) for setting up Batch jobs. Seem like a good place to start?

**Comment by dbohlender** [comment]
Sorry, was preparing for and then attending management meeting.  Those were the instructions that I followed, but only to batch processing.  I've not yet done any batch work.

**Comment by sfabbro** [comment]
> @sfabbro thanks for your help. Could you elaborate on why there should only be one image per VM? Is that just to limit unnecessary downloads of the container image(say, from DockerHub)?

It is not an absolute necessity, but it will save you space given that you only have 20G and docker images are large, especially if you use anaconda.  So the root file system fills up quickly even with the shared layers niceness of docker. If you want to run several simultaneous jobs per VM you will have also to make sure there one job pulling a docker image does not conflict with another job downloading the same docker image on the same VM.
Anyway if you really want to do docker run yourself on the VM, have the image pulled before snapshotting the VM to avoid unnecessary downloads.

**Comment by ijiraq** [comment]
@sfabbro: good insights to docker/containers/images.  I guess in the 'docker run' only the first image that gets loaded to a VM will actually pull from docker-hub, the others will be from the cache.  To make the pull from docker-hub minimal a good root image will help, with just minimal nifty bits coming in at launch time. 

But there are things to think about to make this not an abuse of network.

**Comment by ijiraq** [comment]
> Also to make sure I'm not just going down a rabbit hole, @ijiraq @dbohlender I'm following the instructions [here](https://www.canfar.net/en/docs/quick_start/) for setting up Batch jobs. Seem like a good place to start?

please do follow, and if you find wrong stuff in there take notes so we can update the manual.

**Comment by Nat1405** [comment]
First run of the container on batch mode has happened; now time for tweaking. Added rough notes on my work so far in  d5eebcfd33c715.
