### ISSUE TITLE
Build a NIFTY container

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#2]
Determine how to use Docker to build a container and install the software environment needed to process NIFTS data.

**Comment by Nat1405** [comment]
Hey all, I have a non-interactive version of Nifty4Gemini running in a docker container. It took a bit of manual finangling to get the reduction going. I just want to make sure, is the goal to be able to launch a container (maybe providing a program name) and "press go" to start reducing data?

**Comment by ijiraq** [comment]
The container should be able to start in a way that presents a prompt to the user to start working, maybe with 'bash' as the entry point (normal for our arcade containers).  But having it so that `docker run -t nifty program_id` just ran and did that program, would be very sweet.

**Comment by Nat1405** [comment]
2c705ecac903df5521d877317d73dc8d93fe4669 adds two containers (that can be built from their Dockerfiles); one can be run interactively and launches into a bash shell and the other can be run fully automatically with `docker run -t auto_nifty program_id`. @ijiraq, would we like support for graphical IRAF tasks in the interactive version?

After we figure out interactivity maybe this solves this issue.
