### ISSUE TITLE
Modify nifty to use the cadc-tap system to query files.

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#3]
The CADC archive system uses the [CAOM2 data mode](https://www.opencadc.org/caom2/) to record metadata about observations.  Those can be queried using [cadc-tap](https://pypi.org/project/cadctap/).   Adapt the NIFTY data flow to use that query system and [cadc-data](https://pypi.org/project/cadcdata/) to retrieve that files from the CADC archive.

**Comment by ijiraq** [comment]
You might want to use pyVO and astroquery.cadc  rather that cadc-tap and cadc-data directly.

**Comment by Nat1405** [comment]
I've updated Nifty to support CADC downloads in [this pull request](https://github.com/Nat1405/Nifty4Gemini/pull/4). Fixed a few Nifty4Gemini bugs while I was in there as well! Would we eventually like to deploy this to pip for our containers to pull?
