### ISSUE TITLE
Run docker on a VM to allow batch processing based on container

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#5]
The project is using a container environment to install the nifty package so that container can be used in Arcade for interactive mode.  But we also want to do batch processing, to achieve that we could run Docker in a VM that is the launched via the regular batch scheduler. 

This course might help you learn how to do this:  https://wgschool.netlify.app/docker is being offered the week of June 29th.  Register here: https://wgschool.netlify.app/attendee/

**Comment by Nat1405** [comment]
This is fantastic, thank you very much. Honestly, it feels fantastic to get paid to do things like this!

You mention we're hoping to do batch processing at some point; does this mean I should request batch processing capabilities in my CANFAR account creation request?

Cheers,
Nat
