### ISSUE TITLE
Get data information from CADC services

### ISSUE THREAD

**Issue by ijiraq** [ijiraq/gemini_processing#7]
Utilize the CADC TAP service and CAOM content to gather the NIFS files needed for processing.

**Comment by Nat1405** [comment]
This is potentially finished; nifty is using the query "SELECT observationID, publisherID, productID FROM caom2.Observation AS o JOIN caom2.Plane AS p ON o.obsID=p.obsID WHERE instrument_name='NIFS' AND proposal_id='\<proposal ID\>' to get all data associated with a given proposal. Nifty then does its own sorting of this data to determine what it needs for a reduction.

**Comment by ijiraq** [comment]
Cool. Is that code now inside NIFTY or can it be externalize? Not sure where the boundary between what is in NIFTY and what is in the script that will run the processing should be.

**Comment by Nat1405** [comment]
Awesome. Right now it's inside NIFTY (Nifty has plenty of helper functions in a "utilities" file so I just added it there) but I tested this first with an external script. In principle all NIFTY needs to know is the directory where it can find raw files and it can go from there.
